protected/models/Bank.php
<?php

/**
 * This is the model class for table "tbl_bank".
 *
 * The followings are the available columns in table 'tbl_bank':
 * @property string $id
 * @property string $name
 * @property string $acc_number
 * @property string $acc_name
 * @property string $image
 * @property integer $status
 */
class Bank extends CActiveRecord
{
        const SMALL_THUMB_WIDTH=120;
	const SMALL_THUMB_HEIGHT=36;

	const LARGE_THUMB_WIDTH=280;
	const LARGE_THUMB_HEIGHT=120;
        
        private $_small_url;
	private $_large_url;
        
        public function getStatusname()
        {
            switch($this->status)
            {
                case '1':
                    return 'Online';
                    break;
                case '0':
                    return 'Offline';
                    break;
            }
        }
        
        public function getFullname()
        {
           return $this->name.' '.$this->acc_number; 
        }
        
        public static function statusList()
        {
            return array(
                1=>'Online',
                0=>'Offline'
            );
        }
        
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_bank';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, acc_number, acc_name', 'required'),
			array('name, acc_number', 'length', 'max'=>20),
			array('acc_name', 'length', 'max'=>30),
                        array('image', 'length', 'max'=>100),
                        array('status', 'numerical', 'integerOnly'=>true),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, acc_number, acc_name, image, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'acc_number' => 'Acc Number',
			'acc_name' => 'Acc Name',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('acc_number',$this->acc_number,true);
		$criteria->compare('acc_name',$this->acc_name,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Bank the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        public function afterSave()
	{
            if(!empty($this->image))
            {
                
                    //generate small
                    $this->generateThumb(self::SMALL_THUMB_WIDTH,self::SMALL_THUMB_HEIGHT,Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/small_'.$this->image);
                    //generate large thumbnail
                    $this->generateThumb(self::LARGE_THUMB_WIDTH,self::LARGE_THUMB_HEIGHT,Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/large_'.$this->image);
                
            }	            
	}
        
        protected function beforeDelete() {
            parent::beforeDelete();
            $this->SureRemoveDir($this->getDirUrl());
            return TRUE;
        }
        
        public function getImgurl()
        {
            return Yii::app()->baseUrl.'/archives/tmp/b'.$this->id.'/';
        }
        
        public function getSmall_url()
	{
		if($this->_small_url===NULL)
		{
			$this->_small_url=self::generateThumbUrl($this->image,'archives/tmp/b'.$this->id.'/'.$this->image,'small');
		}
		return $this->_small_url;
	}

	public function getLarge_url()
	{
		if($this->_large_url===NULL)
		{
			$this->_large_url=self::generateThumbUrl($this->image,'archives/tmp/b'.$this->id.'/'.$this->image,'large');
		}
		return $this->_large_url;
	}
        
        protected function generateThumb($width,$height,$path)
	{
		$thumb=Yii::app()->iwi->load(Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/'.$this->image)
                        ->adaptive($width,$height)
                        ->save($path);
	}
        
        public static function generateThumbUrl($filename,$url,$sizeType)
	{
		return str_replace($filename, '', $url).$sizeType.'_'.$filename;
	}
        
        public function onBeforeDelete($event)
	{
		$filepath=Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/'.$this->image;
		if(is_file($filepath))
			unlink($filepath);
		parent::onBeforeDelete($event);
	}
        
        protected function SureRemoveDir($dir) {
            if(!$dh = @opendir($dir)) return;
            while (false !== ($obj = readdir($dh))) {
                if($obj=='.' || $obj=='..') continue;
                if (!@unlink($dir.'/'.$obj)) SureRemoveDir($dir.'/'.$obj, true);
            }
            //closedir($dh);            
            @rmdir($dir);           
        }
        
        public function getDirUrl()
        {
            $link_dir = str_replace('protected','',Yii::app()->basePath);
              return $link_dir.'archives/tmp/b'.$this->id;
        }
}

protected/models/Reward.php
<?php

/**
 * This is the model class for table "tbl_reward".
 *
 * The followings are the available columns in table 'tbl_reward':
 * @property string $id
 * @property string $member_id
 * @property integer $debit
 * @property string $reward
 * @property integer $status
 * @property string $approved_on
 * @property string $created_on
 *
 * The followings are the available model relations:
 * @property Member $member
 */
class Reward extends CActiveRecord
{
        public $val;
        
        public function getStatusname()
        {
            switch($this->status)
            {
                case '1':
                    return 'Processed';
                    break;
                case '0':
                    return 'Pending';
                    break;
            }
        }
        
        public function getPosted()
        {
            $formatter = Yii::app()->getDateFormatter();
            $format = Yii::app()->getLocale()->getDateFormat('medium',true,true);
                return $formatter->format($format, $this->created_on);
        }
        
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_reward';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('member_id, debit, reward', 'required'),
			array('debit, status', 'numerical', 'integerOnly'=>true),
			array('member_id', 'length', 'max'=>10),
			array('reward', 'length', 'max'=>100),
			array('approved_on', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, member_id, debit, reward, status, approved_on, created_on', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'member' => array(self::BELONGS_TO, 'Member', 'member_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'member_id' => 'Member',
			'debit' => 'Debit',
			'reward' => 'Reward',
			'status' => 'Status',
			'approved_on' => 'Approved On',
			'created_on' => 'Created On',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('member_id',$this->member_id,true);
		$criteria->compare('debit',$this->debit);
		$criteria->compare('reward',$this->reward,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('approved_on',$this->approved_on,true);
		$criteria->compare('created_on',$this->created_on,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Reward the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        public function getTotal()
        {
            $var_sum = self::model()->findBySql("select sum(`debit`) as `val` from `tbl_reward` where `member_id`=:id", array(':id'=>Yii::app()->member->id));
            return $var_sum->val;
        }
        
        public function getReward()
        {
            $var_sum = self::model()->findBySql("select MAX(`debit`) as `val` from `tbl_reward` where `member_id`=:id", array(':id'=>Yii::app()->member->id));
            if($var_sum->val)
                $sum=$var_sum->val;
            else
                $sum=0;
            
            $reward=RewardSetting::model()->find('pv>:pv',[':pv'=>$sum]);
            $member= Yii::app()->member->model;
            if($member->total_left>=$reward->pv&& $member->total_right>=$reward->pv)
                return $reward;
            else
                return false;
           
        }
}

protected/views/apps/member/_form.php
<?php
/* @var $this MembersController */
/* @var $model Member */
/* @var $form CActiveForm */
?>
<style>
    label {display: inline !important;}
</style>
<?php $form=$this->beginWidget('CActiveForm', array(
                                'id'=>'validation',
                                'enableAjaxValidation'=>false,
                        )); ?>
                        <?php echo $form->errorSummary($model);?>
                   <div class="span11">
                       <?php if(!$model->isNewRecord):?>
                        <div class="ushort clearfix">
                            <?php echo CHtml::link($model->name,array('view','id'=>$model->id));?>
                                                        <a href="#"><?php echo CHtml::image(Yii::app()->baseUrl.'/'.$model->main_url, 'img'.$model->id,array('class'=>'img-polaroid'));?></a>
                        </div> 
                       <?php endif;?>

                        <div class="block-fluid without-head">
                            <div class="toolbar nopadding-toolbar clearfix">
                                <h4>Member Form</h4>
                            </div>    
                            
                            <div class="row-form clearfix">
                                <div class="span3">Membership</div>
                                <div class="span9"><?php $tp = array('0'=>'&nbsp;Silver (35PV)','1'=>'&nbsp;Gold (100PV)', '2'=>'&nbsp;Platinum (300PV)', '3'=>'&nbsp;Diamond (700PV)');
                        echo $form->radioButtonList($model,'type',$tp,array('uncheckValue' => '','separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;','class'=>'type','required'=>'required'));?></div>
                            </div>
                            <?php if($model->isNewRecord):?>
                            <div class="row-form clearfix">
                                <div class="span3">Sponsor*</div>
                                <div class="span9">
                                <?php $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
                                        'model'=>$model,
                                        'attribute'=>'id_member',
                                        'source'=>$this->createUrl('loadupmember',['up'=>$_GET['upline']]),
                                        'options'=>array(
                                            'showAnim'=>'fold',
                                            'select'=>"js:function(event, ui) {
                                                                              $(this).val(ui.item.value);
                                                                              $('#Member_sponsor_mid').val(ui.item.mid);
                                                                            }"
                                            
                                        ),
                                        'cssFile'=>false,
                                        'htmlOptions'=>array('class'=>'form-control  form-control--contact validate[required]','placeholder'=>'Type Sponsor ID','required'=>'required')
                                    ));?>
                                    <input type="hidden" value="" name="Member[sponsor_mid]" id="Member_sponsor_mid" placeholder="" required="required">
                        <?php echo $form->error($model,'sponsor_mid'); ?>
                                </div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Upline</div>
                                <div class="span9"><?= $upId;?></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Position</div>
                                <div class="span9"><?= $pos;?></div>
                            </div>
                            <?php endif;?>
                            <div class="row-form clearfix">
                                <div class="span3">Email*</div>
                                <div class="span9"><?php echo $form->emailField($model,'email',array('maxlength'=>50,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'email'); ?></span></div>
                            </div>
                            <?php if($model->isNewRecord):?>
                            <div class="row-form clearfix">
                                <div class="span3">Password*</div>
                                <div class="span9"><?php echo $form->passwordField($model,'password',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'password'); ?></span></div>
                            </div>
                            
                            <div class="row-form clearfix">
                                <div class="span3">Re-Password*</div>
                                <div class="span9"><?php echo $form->passwordField($model,'repassword',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'repassword'); ?></span></div>
                            </div>
                            <?php endif;?>
                            
                            <div class="row-form clearfix">
                                <div class="span3">Name*</div>
                                <div class="span9"><?php echo $form->textField($model,'name',array('maxlength'=>50,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'name'); ?></span></div>
                            </div>
                            
                            <div class="row-form clearfix">
                                <div class="span3">Gender*</div>
                                <div class="span9"><?php $sex = array('1'=>'Male', '0'=>'Female');
                                echo $form->radioButtonList($model,'gender',$sex,array('uncheckValue' => '','separator'=>'&nbsp;&nbsp;','class'=>'gender','required'=>'required'));?></div>
                            </div> 
                            
                            
                                            
                            <div class="row-form clearfix">
                                <div class="span3">Address*</div>
                                <div class="span9"><?php echo $form->textArea($model,'address',array('rows'=>3, 'cols'=>30,'class'=>'validate[required]')); ?><span><?php echo $form->error($model,'address'); ?></span></div>
                            </div>                       
                            
                            <div class="row-form clearfix">
                                <div class="span3">Region*</div>
                                <div class="span9"><?php echo $form->textField($model,'region',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'region'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">City</div>
                                <div class="span9"><?php echo $form->textField($model,'city',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'city'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Post Code*</div>
                                <div class="span9"><?php echo $form->textField($model,'post_code',array('size'=>5,'maxlength'=>5,'class'=>'validate[required]','required'=>'required')); ?></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Phone*</div>
                                <div class="span9"><?php echo $form->telField($model,'mobile_phone',array('maxlength'=>15,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'mobile_phone'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Bank Name*</div>
                                <div class="span9"><?php echo $form->textField($model,'bank',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'bank'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Account Number*</div>
                                <div class="span9"><?php echo $form->numberField($model,'account_number',array('maxlength'=>20,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'account_number'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Account Name*</div>
                                <div class="span9"><?php echo $form->textField($model,'account_name',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'account_name'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Heir Name*</div>
                                <div class="span9"><?php echo $form->textField($model,'heir_name',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'heir_name'); ?></span></div>
                            </div>
                            <div class="row-form clearfix">
                                <div class="span3">Heir Relation*</div>
                                <div class="span9"><?php echo $form->textField($model,'heir_relation',array('maxlength'=>30,'class'=>'validate[required]','required'=>'required')); ?><span><?php echo $form->error($model,'heir_relation'); ?></span></div>
                            </div>
                            
                            <?php if(!$model->isNewRecord):?>
                            <div class="row-form clearfix">
                                <div class="span3">Sponsor*</div>
                                <div class="span9">
                                <?php $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
                                        'model'=>$model,
                                        'attribute'=>'id_sponsor',
                                        'source'=>$this->createUrl('loadallmember',['up'=>$model->upline_id]),
                                        'options'=>array(
                                            'showAnim'=>'fold',
                                            'select'=>"js:function(event, ui) {
                                                                              $(this).val(ui.item.value);
                                                                              $('#Member_sponsor_id').val(ui.item.id);
                                                                            }"
                                            
                                        ),
                                        'cssFile'=>false,
                                        'htmlOptions'=>array('class'=>'form-control  form-control--contact validate[required]','placeholder'=>'Type Sponsor ID','required'=>'required')
                                    ));?>
                                    <input type="hidden" value="" name="Member[sponsor_id]" id="Member_sponsor_id" placeholder="" required="required">
                        <?php echo $form->error($model,'sponsor_mid'); ?>
                                </div>
                            </div>
                            <?php endif;?>
                            <div class="footer tar">
                                <?php echo CHtml::link('Cancel','javascript: history.go(-1)',array('class'=>'btn btn-danger'));?>&nbsp;&nbsp;&nbsp;<?php echo CHtml::submitButton('Save',array('class'=>'btn')); ?>
                            </div>
                        </div>                    
                    </div>
<?php $this->endWidget(); ?>

protected/views/apps/member/_view.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php if($model):?>
    <?php $i=1; foreach($model as $row):?>
            <tr>
                <td class="uk-text-large uk-text-nowrap"><?=CHtml::link($row->mid,['view','id'=>$row->id]);?></td>
                <td><?= $row->name;?></td>
                <td><?= $row->created;?></td>
                <td><?php echo ($row->status=='0')?'<span class="uk-badge uk-badge-danger">'.$row->statusname.'</span>':'<span class="uk-badge uk-badge-success">'.$row->statusname.'</span>';?></td>
                <td class="uk-text-nowrap">
                    <?php if($row->status!=='2'):?><?php echo CHtml::link('<i class="md-icon material-icons">&#xE254;</i>',array('update','id'=>$row->id));?><?php endif;?>
                    <?php if($row->status=='0' || $row->status=='2' || $row->status=='3'):?><a href="#" class="activate" data-id="<?php echo $row->id;?>" title="Activate"><i class="md-icon material-icons">spellcheck</i></a><?php endif;?>
                    <?php if($row->status==1):?><a href="#" class="del" data-id="<?php echo $row->id;?>"><i class="md-icon material-icons">&#xE872;</i></a><?php endif;?>
                </td>
            </tr>
    <?php $i++; endforeach;?>
<?php else:?>
            <tr>
                <td colspan="8"><p><?= $title;?> Member is unavailable.</p></td>
            </tr>
<?php endif; ?>

protected/views/apps/member/_viewBank.php
<?php
/* @var $this MembersController */
/* @var $data Member */
?>

<?php if($model):?>
                                 <?php foreach($model as $row):?>
                                    <tr>                                    
                                        <td width="60">
                                            <?php echo CHtml::link(CHtml::image(Yii::app()->baseUrl.'/'.$row->member->main_url, 'img'.$row->id,array('class'=>'img-polaroid','style'=>'width:42px;max-height:42px;')),array('view','id'=>$row->id));?>
                                            
                                        </td>
                                        <td>
                                            <?php echo CHtml::link($row->member->mid.' - '.$row->member->name,array('view','id'=>$row->member->id),array('class'=>'user'));?>
                                            <p class="about">
                                                <span class="icon-home" title="Name"></span> <?php echo $row->bank;?> <br/>
                                                <span class="icon-th-list" title="Email"></span> <?php echo $row->account_number;?> <br/>
                                                <span class="icon-user" title="Phone"></span> <?php echo $row->account_name;?>
                                            </p>
                                        </td>
                                        <td width="320">
                                            <p class="info">
                                                <a href="javascript:void(0);" class="app" data-id="<?php echo $row->id;?>"><span class="icon-ok"></span> <span class="green">Approve?</span></a><br/>
                                                <a href="javascript:void(0);" class="del" data-id="<?php echo $row->id;?>"><span class="icon-remove"></span> <span class="red">Reject?</span></a><br/><br>
                                                <span class="icon-calendar"></span> <span class="blue"><?php echo $row->posted;?></span>
                                            </p>
                                        </td>
                                    </tr>
                                 <?php $i++; endforeach;?>
                                 <?php else:?>
                                    <tr>
                                        <td colspan="6">Change account request is unavailable.</td>
                                    </tr>
                                 <?php endif;?>

protected/views/apps/member/bank.php
<?php
/* @var $this MembersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Change Bank Account Request',
);
?>

<div class="workplace">
                <div class="page-header">
                    <h1>Change Bank Account Request <small>List</small></h1>
                </div>
                <?php Notify::renderFlash();?>
                
                <div class="row-fluid">

                    <div class="span12">                    
                        <div class="head clearfix">
                            <div class="isw-grid"></div>
                            <h1>Change Bank Account Request</h1>             
                        </div>
                        <div class="block-fluid">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table listUsers">
                                <tbody>
                                    <?php $this->renderPartial('_viewBank',array('model'=>$model,'i'=>$i));?>                              
                                </tbody>
                            </table>   
                            <?php if($count>10):?>
                            <div class="pagination right">
                            <?php 
                            $this->widget('CLinkPager', array(
                                'pages' => $pages,
                                'header'=>'',
                                'footer'=>'',
                                'nextPageLabel'=>'»',
                                'prevPageLabel'=>'«',
                                'id'=>'link_pager',
                            ))?>
                            </div>
                            <?php endif;?>
                        </div>
                        
                    </div>           

                </div>            

                <div class="dr"><span></span></div>  
            </div>

<?php Yii::app()->clientScript->registerScript('delete-members', "
    $('.app').live('click',function(){
        if(!confirm('Are you sure want to APPROVE this request?')) return false;
        var id=$(this).attr('data-id');
        $.ajax({
            url:'".$this->createUrl('apps/member/apprequest')."',
            type: 'GET',
            data: 'id='+id,
            success:function(){
                window.location.href = '".$this->createUrl('apps/member/bankaccount')."'; 
            }
        });
    return false;
    });
    
    $('.del').live('click',function(){
        if(!confirm('Are you sure want to REJECT this request??')) return false;
        var id=$(this).attr('data-id');
        $.ajax({
            url:'".$this->createUrl('apps/member/rejectrequest')."',
            type: 'GET',
            data: 'id='+id,
            success:function(){
                window.location.href = '".$this->createUrl('apps/member/bankaccount')."'; 
            }
        });
    return false;
    });
    
",CClientScript::POS_READY);?>

protected/views/apps/member/create.php
<?php
/* @var $this NewsController */
/* @var $model Content */

$this->breadcrumbs=array(
	'Member'=>array('index'),
	'Create',
);
?>

<div class="workplace">
                <div class="page-header">
                    <h1><small>Add</small> Member</h1>
                </div>
                <div class="row-fluid">
                    <?php echo $this->renderPartial('_form', array('model'=>$model,'upId'=>$upId,'pos'=>$pos)); ?>
                </div>
                <div class="dr"><span></span></div>  
            </div>