protected/models/Bank.php
<?php

/**
 * This is the model class for table "tbl_bank".
 *
 * The followings are the available columns in table 'tbl_bank':
 * @property string $id
 * @property string $name
 * @property string $acc_number
 * @property string $acc_name
 * @property string $image
 * @property integer $status
 */
class Bank extends CActiveRecord
{
        const SMALL_THUMB_WIDTH=120;
	const SMALL_THUMB_HEIGHT=36;

	const LARGE_THUMB_WIDTH=280;
	const LARGE_THUMB_HEIGHT=120;
        
        private $_small_url;
	private $_large_url;
        
        public function getStatusname()
        {
            switch($this->status)
            {
                case '1':
                    return 'Online';
                    break;
                case '0':
                    return 'Offline';
                    break;
            }
        }
        
        public function getFullname()
        {
           return $this->name.' '.$this->acc_number; 
        }
        
        public static function statusList()
        {
            return array(
                1=>'Online',
                0=>'Offline'
            );
        }
        
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_bank';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, acc_number, acc_name', 'required'),
			array('name, acc_number', 'length', 'max'=>20),
			array('acc_name', 'length', 'max'=>30),
                        array('image', 'length', 'max'=>100),
                        array('status', 'numerical', 'integerOnly'=>true),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, acc_number, acc_name, image, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'acc_number' => 'Acc Number',
			'acc_name' => 'Acc Name',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('acc_number',$this->acc_number,true);
		$criteria->compare('acc_name',$this->acc_name,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Bank the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        public function afterSave()
	{
            if(!empty($this->image))
            {
                
                    //generate small
                    $this->generateThumb(self::SMALL_THUMB_WIDTH,self::SMALL_THUMB_HEIGHT,Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/small_'.$this->image);
                    //generate large thumbnail
                    $this->generateThumb(self::LARGE_THUMB_WIDTH,self::LARGE_THUMB_HEIGHT,Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/large_'.$this->image);
                
            }	            
	}
        
        protected function beforeDelete() {
            parent::beforeDelete();
            $this->SureRemoveDir($this->getDirUrl());
            return TRUE;
        }
        
        public function getImgurl()
        {
            return Yii::app()->baseUrl.'/archives/tmp/b'.$this->id.'/';
        }
        
        public function getSmall_url()
	{
		if($this->_small_url===NULL)
		{
			$this->_small_url=self::generateThumbUrl($this->image,'archives/tmp/b'.$this->id.'/'.$this->image,'small');
		}
		return $this->_small_url;
	}

	public function getLarge_url()
	{
		if($this->_large_url===NULL)
		{
			$this->_large_url=self::generateThumbUrl($this->image,'archives/tmp/b'.$this->id.'/'.$this->image,'large');
		}
		return $this->_large_url;
	}
        
        protected function generateThumb($width,$height,$path)
	{
		$thumb=Yii::app()->iwi->load(Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/'.$this->image)
                        ->adaptive($width,$height)
                        ->save($path);
	}
        
        public static function generateThumbUrl($filename,$url,$sizeType)
	{
		return str_replace($filename, '', $url).$sizeType.'_'.$filename;
	}
        
        public function onBeforeDelete($event)
	{
		$filepath=Yii::app()->basePath.'/../archives/tmp/b'.$this->id.'/'.$this->image;
		if(is_file($filepath))
			unlink($filepath);
		parent::onBeforeDelete($event);
	}
        
        protected function SureRemoveDir($dir) {
            if(!$dh = @opendir($dir)) return;
            while (false !== ($obj = readdir($dh))) {
                if($obj=='.' || $obj=='..') continue;
                if (!@unlink($dir.'/'.$obj)) SureRemoveDir($dir.'/'.$obj, true);
            }
            //closedir($dh);            
            @rmdir($dir);           
        }
        
        public function getDirUrl()
        {
            $link_dir = str_replace('protected','',Yii::app()->basePath);
              return $link_dir.'archives/tmp/b'.$this->id;
        }
}

protected/models/Card.php
<?php

/**
 * This is the model class for table "tbl_card".
 *
 * The followings are the available columns in table 'tbl_card':
 * @property string $id
 * @property string $serial
 * @property string $pin
 * @property integer $type
 * @property integer $status
 * @property string $member_id
 * @property integer $is_active
 * @property string $expired_on
 * @property string $created_by
 * @property string $created_on
 *
 * The followings are the available model relations:
 * @property Member[] $members
 */
class Card extends CActiveRecord
{
        public $value;
        public $val;
        
        public function getStatusname()
        {
            switch($this->status)
            {
                case '1':
                    return 'Yes';
                    break;
                case '0':
                    return 'No';
                    break;
            }
        }
       
        public function getIsActive()
        {
            switch($this->is_active)
            {
                case '1':
                    return '<span style="display:inherit;padding: 5px; background-color:green;color:#fff;">Active</span>';
                    break;
                case '0':
                    return '<span style="display:block;padding: 5px; background-color:red;">Activated</span>';
                    break;
            }
        }
        
        public static function statusList()
        {
            return array(
                1=>'Active',
                0=>'Inactive'
            );
        }
        
        public static function typeList()
        {
            return array(
                1=>'Standard',
                2=>'Premium',
                3=>'Deluxe',
                4=>'Executive',
                5=>'Executive Diamond'
            );
        }

        public function getTypename()
        {
            switch($this->type)
            {
                case '1':
                    return 'Standard';
                    break;
                case '2':
                    return 'Deluxe';
                    break;
                case '3':
                    return 'Premium';
                    break;
                case '4':
                    return 'Executive';
                    break;
                case '5':
                    return 'Executive Diamond';
                    break;
            }
        }
        
        public function getOwner()
        {
            $data=Member::model()->findByAttributes(array('card_id'=>$this->id));
            if($data)
            {
                    return CHtml::link($data->mid,array('apps/member/view','id'=>$data->id));
            }
            else
                return '-';
        }
        
        public function getOwnermember()
        {
            $data=Member::model()->findByAttributes(array('card_id'=>$this->id));
            if($data)
            {
                    return array(CHtml::link($data->mid,array('/member/genealogy','id'=>$data->id)),$data->name,$data->country->name,$data->created_on);
            }
            else
                return '-';
        }
        
        public function getMemberPin($id)
        {
            return self::model()->countByAttributes(array('member_id'=>$id));
        }
        
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_card';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('status, type, is_active', 'numerical', 'integerOnly'=>true),
			array('serial', 'length', 'max'=>50),
			array('pin', 'length', 'max'=>15),
			array('member_id, created_by', 'length', 'max'=>10),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, serial, pin, status, member_id, is_active, expired_on, type, created_by, created_on', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
                        'member' => array(self::BELONGS_TO, 'Member', 'member_id'),
			'members' => array(self::HAS_MANY, 'Member', 'card_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'serial' => 'Serial Number',
			'pin' => 'Pin',
			'status' => 'Status',
			'is_active' => 'Is Active',
			'expired_on' => 'Expired On',
			'created_by' => 'Created By',
			'created_on' => 'Created On',
            'type'=>'Type',
                        'value' => 'Jumlah PIN'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('serial',$this->serial,true);
		$criteria->compare('pin',$this->pin,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('is_active',$this->is_active);
		$criteria->compare('expired_on',$this->expired_on,true);
		$criteria->compare('created_by',$this->created_by,true);
		$criteria->compare('created_on',$this->created_on,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Card the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        protected function  beforeSave() 
        {
            parent::beforeSave();
            if($this->isNewRecord)
            {
                $this->serial = $this->generateRandomString();
                $this->pin = mt_rand(100000,999999);
                $this->expired_on=date('Y-m-d', strtotime("+2 year"));
                $this->created_by=Yii::app()->user->id;
            }
            return TRUE;
        }
        
        protected function generateRandomString($length = 8) {
            $characters = '123456789ABCDEFGHIJKLMNPQRSTUVWXYZ';
            $charactersLength = strlen($characters);
            $randomString = '';
            for ($i = 0; $i < $length; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            return $randomString;
        }
        
        public function getTotal()
        {
            $var_sum = self::model()->findBySql("select count(`id`) as `val` from `tbl_card` where `member_id`=:id", array(':id'=>Yii::app()->member->id));
            return $var_sum->val;
        }

        public function getTotalType($data)
        {
            $var_sum = self::model()->findBySql("select count(`id`) as `val` from `tbl_card` where `member_id`=:id and `type`=:data", array(':id'=>Yii::app()->member->id,':data'=>$data));
            return $var_sum->val;
        }
        
        public function getTotalPin($st=null)
        {
            if($st===null)
                $var_sum = self::model()->findBySql("select count(`id`) as `val` from `tbl_card`");
            else
                $var_sum = self::model()->findBySql("select count(`id`) as `val` from `tbl_card` where status=:st",array(':st'=>$st));
            return $var_sum->val;
        }
        
        public function getTotalStock($tp=null)
        {
            if($tp===null)
                $var_sum = self::model()->findBySql("select count(`id`) as `val` from `tbl_card` WHERE member_id IS NULL AND status=0");
            else
                $var_sum = self::model()->findBySql("select count(`id`) as `val` from `tbl_card` WHERE type=:tp AND member_id IS NULL AND status=0",array(':tp'=>$tp));
            return $var_sum->val;
        }
        
}

protected/views/apps/upgrademember/_view.php
                                <?php if($model):?>
                                 <?php foreach($model as $row):?>
                                    <tr>                                    
                                        <td><?php echo $i;?></td>
                                        <td><?php echo CHtml::link($row->member->mid.' - '.$row->member->fullname,['/apps/member/view','id'=>$row->member_id]);?></td>
                                        <td><?php echo number_format($row->value);?></td>
                                        <td><?php echo $row->bank_receiver;?></td>
                                        <td><?php echo $row->bank_sender;?></td>
                                        <td><?php echo $row->account_name;?></td>
                                        <td><?php echo $row->date;?></td>
                                        <td><?php echo $row->statusname;?></td>
                                        <?php if($row->status=='0'):?>
                                        <td>
                                            <?= CHtml::link('<i class="md-icon material-icons">&#xE5CA;</i>',['approve','id'=>$row->id],['class'=>'app']);?>
                                        </td>   
                                        <td>
                                                <a href="#" class="del" data-id="<?php echo $row->id;?>"><i class="md-icon material-icons">&#xE872;</i></a>
                                        </td>   
                                        <?php endif;?>
                                    </tr>
                                 <?php $i++; endforeach;?>
                                 <?php else:?>
                                    <tr>
                                        <td colspan="9">Membership confirmation is unavailable.</td>
                                    </tr>
                                 <?php endif;

protected/views/apps/upgrademember/index.php
<div id="page_content">
        <div id="page_heading">
            <h1><?=$title;?> Upgrade Confirmation</h1>
        </div>
        <div id="page_content_inner">
            <?php Notify::renderFlash();?>
            <div class="md-card">
                <div class="md-card-content">
                    <?php echo CHtml::form(array('/apps/upgradeMember/search'), 'GET',array('class'=>'search'));?>
                    <div class="uk-grid" data-uk-grid-margin="">
                        
                        <div class="uk-width-medium-8-10">
                            <label for="order_search">Key</label>
                            <?php echo CHtml::textField('q', '', array('class'=>'md-input','id'=>'order_search'));?>
                        </div>
                        
                        <div class="uk-width-medium-2-10 uk-text-center">
                            <button type="submit" class="md-btn md-btn-primary uk-margin-small-top">Search</button>
                        </div>
                        
                    </div>
                    <?php echo CHtml::endForm();?>
                </div>
            </div>
            <div class="md-card">
                <div class="md-card-content">
                    
                    <div class="uk-grid" data-uk-grid-margin>
                        <div class="uk-width-1-1">
                            <div class="uk-overflow-container">
                                <table class="uk-table">
                                    <thead>
                                        <tr>
                                            <th width="2%">#</th>
                                            <th>Member</th>
                                            <th>Amount (IDR)</th>
                                            <th>Bank Receiver</th>
                                            <th>Bank Sender</th>
                                            <th>Account Name</th>
                                            <th>Date</th>
                                            <th>Status</th>
                                            <?php if($title=='New'):?>
                                            <th>Approve</th>
                                            <th>Delete</th>
                                            <?php endif;?>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $this->renderPartial('_view',array('model'=>$model,'i'=>$i));?>
                                    </tbody>
                                </table>
                            </div>
                            <?php if($count>10):?>
                            <div class="uk-pagination uk-margin-medium-top uk-margin-medium-bottom">
                            <?php 
                            $this->widget('CLinkPager', array(
                                'pages' => $pages,
                                'header'=>'',
                                'footer'=>'',
                                'nextPageLabel'=>'»',
                                'prevPageLabel'=>'«',
                                'id'=>'link_pager',
                            ))?>
                            </div>
                            <?php endif;?>
                        </div>
                    </div>
                    <?php if($title=='Processed'):?>
                    <?= CHtml::endForm();?>
                    <?php endif;?>
                </div>
            </div>

        </div>
    </div>

<?php 
if(isset($_GET['type']))
    $tpage=$_GET['type'];
else
    $tpage='new';

Yii::app()->clientScript->registerScript('delete-pay', "
    $('.app').on('click',function(){
        if(!confirm('Are you sure want to APPROVE this upgrade payment confirmation?')) return false;
        
    });
    
    $('.del').on('click',function(){
        if(!confirm('Are you sure want to DELETE this upgrade payment confirmation?')) return false;
        var id=$(this).attr('data-id');
        $.ajax({
            url:'".$this->createUrl('apps/upgradeMember/delete')."',
            type: 'GET',
            data: 'id='+id,
            success:function(){
                window.location.href = '".$this->createUrl('apps/upgradeMember',['type'=>$tpage])."'; 
            }
        });
    return false;
    });
",CClientScript::POS_READY);?>

protected/views/apps/upgrademember/view.php
<div id="page_content">
        <div id="page_content_inner">

            <div class="uk-width-medium-10-10 uk-container-center reset-print">
                <div class="uk-grid uk-grid-collapse" data-uk-grid-margin>
                    <div class="uk-width-large-7-10">
                        <div class="md-card md-card-single main-print" id="invoice" style="opacity: 1; transform: scale(1);">
                            <div id="invoice_preview">
        <div class="md-card-toolbar">
            <div class="md-card-toolbar-actions hidden-print">
                <i class="md-icon material-icons" id="invoice_print"></i>
                <div class="md-card-dropdown" data-uk-dropdown="">
                    <i class="md-icon material-icons"></i>
                    <div class="uk-dropdown uk-dropdown-flip uk-dropdown-small">
                        <ul class="uk-nav">
                            <li><a href="#">Archive</a></li>
                            <li><a href="#" class="uk-text-danger">Remove</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <h3 class="md-card-toolbar-heading-text large" id="invoice_name">
                Package Order Detail, No. <?= $model->code;?>
            </h3>
        </div>
        <div class="md-card-content" >
            <div class="uk-margin-medium-bottom">
                <span class="uk-text-muted uk-text-small uk-text-italic">Date:</span> <?= $model->posted;?>
                <br>
                <span class="uk-text-muted uk-text-small uk-text-italic">Status:</span> <?php echo ($model->status=='0')?'<span class="uk-badge uk-badge-warning">'.$model->statusname.'</span>':'<span class="uk-badge uk-badge-success">'.$model->statusname.'</span>';?>
                <?php if($model->status=='2'):?>
                <br>
                <span class="uk-text-muted uk-text-small uk-text-italic">Resi Number:</span> <span class="uk-badge uk-badge-warning"><?= $model->resi;?></span>
                <br>
                <?php endif;?>
            </div>
            <div class="uk-grid" data-uk-grid-margin="">
                <div class="uk-width-small-3-5">
                    <div class="uk-margin-bottom">
                        <span class="uk-text-muted uk-text-small uk-text-italic">To:</span>
                        <address>
                            <p><strong><?= CHtml::link($model->member->fullname.' - '.$model->member->mid,['/apps/member/view','id'=>$model->member_id]);?></strong></p>
                            <p><?= $model->addresss->address;?><br>Kec. <?= $model->addresss->district;?>, <?= $model->addresss->city_type;?> <?= $model->addresss->city;?><br><?= $model->addresss->province;?> - <?= $model->addresss->post_code;?></p>
                            <p>Phone: <?= $model->addresss->mobile_phone;?></p>
                        </address>
                    </div>
                </div>
                <div class="uk-width-small-2-5">
                    <span class="uk-text-muted uk-text-small uk-text-italic">Total:</span>
                    <p class="heading_b uk-text-success">Rp <?= number_format($model->total);?></p>
                    <p class="uk-text-small uk-text-muted uk-margin-top-remove">Unique code Rp <?= $model->unique_code;?></p>
                </div>
            </div>
            <div class="uk-grid uk-margin-large-bottom">
                <div class="uk-width-1-1">
                    <table class="uk-table">
                        <thead>
                        <tr class="uk-text-upper">
                            <th>Product</th>
                            <th class="uk-text-center">Amount</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr class="uk-table-middle">
                                <td>
                                    <span class="uk-text-large"><?= $model->product->code;?></span><br>
                                    <span class="uk-text-muted uk-text-small"><?= $model->product->name;?></span>
                                </td>
                                <td class="uk-text-center">
                                    1
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="uk-grid">
                
                <div class="uk-width-1-2">
                    <span class="uk-text-muted uk-text-big uk-text-italic">Payment Confirmation:</span>
                    <?php if($model->status=='1'):?>
                    <p class="uk-margin-top-remove">
                        Transfer to: <strong><?= $model->bank_receiver;?></strong><br>
                        From to: <strong><?= $model->bank_sender;?></strong><br>
                        Date: <strong><?= $model->date;?></strong><br>
                        Amount: <strong>IDR <?= number_format($model->total + $model->unique_code);?></strong>
                    </p>
                   
                    <?php else:?>
                    <p class="uk-margin-top-remove">-</p>
                    <?php endif;?>
                    <?php if($model->status!=='2'):?>
                    <?php echo CHtml::beginForm(['approve'],'POST');?>
                        <?= CHtml::hiddenField('pid',$model->id);?>
                                                        <button type="submit" class="md-btn md-btn-success" id="process">Process?</button>
                    <?php echo CHtml::endForm(); ?>
                                                        <?php endif;?>
                </div>
            </div>
        </div>
    </div>
                        </div>
                    </div>
                    <div class="uk-width-large-3-10 hidden-print uk-visible-large">
                        <div class="md-list-outside-wrapper">
                            <ul class="md-list md-list-outside invoices_list" id="invoices_list">
                                <li class="heading_list">10 Latest Order</li>
                                <?php if($models):?>
                                <?php foreach($models as $m):?>
                                <li>
                                    <a href="<?= Yii::app()->createUrl('/apps/order/view',['id'=>$m->id]);?>" class="md-list-content" data-invoice-id="1">
                                        <span class="md-list-heading uk-text-truncate">Invoice <?= $m->code;?> <span class="uk-text-small uk-text-muted"><?= $m->posted;?></span></span>
                                        <span class="uk-text-small uk-text-muted">Rp <?= number_format($m->totalPrice);?></span> <?php echo ($m->status=='0')?'<span class="uk-badge uk-badge-warning">'.$m->statusname.'</span>':'<span class="uk-badge uk-badge-success">'.$m->statusname.'</span>';?>
                                    </a>
                                </li>
                                <?php endforeach;?>
                                <?php endif;?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
<?php Yii::app()->clientScript->registerScript('app-member', "
    $('#process').on('click',function(){
        if(!confirm('Are you sure want to process this package order (member will be activated automatically)?')) return false;
    });
",CClientScript::POS_READY);?>