protected/models/User.php
<?php

/**
 * This is the model class for table "h_user".
 *
 * The followings are the available columns in table 'h_user':
 * @property string $id
 * @property string $email
 * @property string $name
 * @property string $password
 * @property string $salt
 * @property string $avatar
 * @property integer $level
 * @property integer $status
 * @property string $last_login
 */
class User extends CActiveRecord
{
	const MANAGER=1;
    const ADMINISTRATOR=2;
    const OPERATOR=3;
    
    const SMALL_THUMB_WIDTH=34;
	const SMALL_THUMB_HEIGHT=33;

	const LARGE_THUMB_WIDTH=82;
	const LARGE_THUMB_HEIGHT=82;
    
    private $_small_url;
    private $_large_url;
    
    public $newPassword;
    /*
     * Return the level of user
     */
    public function getLevelName()
    {
        switch($this->level)
        {
            case self::MANAGER:
                return 'Manager';
                break;
            case self::ADMINISTRATOR:
                return 'Administrator';
                break;
            case self::OPERATOR:
                return 'Operator';
                break;
        }
    }
        
    public function getStatusname()
    {
        switch($this->status)
        {
            case '1':
                return 'Active';
                break;
            case '0':
                return 'InActive';
                break;
        }
    }
    
    public static function statusList()
    {
        return array(
            1=>'Active',
            0=>'InActive'
        );
    }
    
    public static function levelList()
    {
        return array(
            2=>'Administrator',
            3=>'Operator'
        );
    }

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('email, name, password, level, status', 'required'),
			array('level, status', 'numerical', 'integerOnly'=>true),
			array('email, name', 'length', 'max'=>50),
			['email','email'],
			['email','unique'],
			array('password, avatar', 'length', 'max'=>225),
			array('salt', 'length', 'max'=>100),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, email, name, password, salt, avatar, level, status, last_login', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'contents' => array(self::HAS_MANY, 'Content', 'created_by'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'email' => 'Email',
			'name' => 'Name',
			'password' => 'Password',
			'salt' => 'Salt',
			'avatar' => 'Avatar',
			'level' => 'Level',
			'status' => 'Status',
			'last_login' => 'Last Login',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('salt',$this->salt,true);
		$criteria->compare('avatar',$this->avatar,true);
		$criteria->compare('level',$this->level);
		$criteria->compare('status',$this->status);
		$criteria->compare('last_login',$this->last_login,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	protected function beforeSave() {
        parent::beforeSave();
        if($this->isNewRecord)
        {
            $this->salt = $this->generateSalt();
            $this->password = $this->hashPassword($this->password, $this->salt);
        }
        return TRUE;
    }

    public function afterSave()
	{
        if(!empty($this->avatar))
        {
        	Yii::app()->hsnImage->generateThumb(self::SMALL_THUMB_WIDTH,self::SMALL_THUMB_HEIGHT,'users',$this->id,$this->avatar,'small'); 
        	Yii::app()->hsnImage->generateThumb(self::LARGE_THUMB_WIDTH,self::LARGE_THUMB_HEIGHT,'users',$this->id,$this->avatar,'large'); 
        }	            
	}
    
    protected function beforeDelete() {
        parent::beforeDelete();
        Yii::app()->hsnImage->SureRemoveDir('users',$this->id);
        return TRUE;
    }

        /**
	 * Checks if the given password is correct.
	 * @param string the password to be validated
	 * @return boolean whether the password is valid
	 */
	public function validatePassword($password)
	{
		return $this->hashPassword($password,$this->salt)===$this->password;
	}

	/**
	 * Generates the password hash.
	 * @param string password
	 * @param string salt
	 * @return string hash
	 */
	public function hashPassword($password,$salt)
	{
		return sha1($salt.$password);
	}
        
        /**
	 * Generates a salt that can be used to generate a password hash.
	 * @return string the salt
	 */
	protected function generateSalt()
	{
		return uniqid('',true);
	}
        
    public function getImgurl(){
        return Yii::app()->hsnImage->getUrl('users',$this->id).$this->avatar;
    }
        
    public function getSmall_url()
	{
		if($this->_small_url===NULL)
		{
			$this->_small_url=Yii::app()->hsnImage->generateThumbUrl($this->avatar,'users',$this->id,'small');
		}
		return Yii::app()->baseUrl.'/'.$this->_small_url;
	}

	public function getLarge_url()
	{
		if($this->_large_url===NULL)
		{
			$this->_large_url=Yii::app()->hsnImage->generateThumbUrl($this->avatar,'users',$this->id,'large');
		}
		return Yii::app()->baseUrl.'/'.$this->_large_url;
	}
}

protected/views/apps/user/_form.php
            <?=$form->errorSummary($model);?>
            <div class="md-card">
                <div class="md-card-content large-padding">
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($model,'name'); ?>
                    <?php echo $form->textField($model,'name',array('maxlength'=>30,'class'=>'md-input','required'=>'required')); ?>
                    <?php echo $form->error($model,'name'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($model,'email'); ?>
                    <?php echo $form->emailField($model,'email',array('maxlength'=>50,'class'=>'md-input','required'=>'required')); ?>
                    <?php echo $form->error($model,'email'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($model,'newPassword'); ?>
                    <?php echo $form->passwordField($model,'newPassword',array('maxlength'=>30,'class'=>'md-input')); ?><span><em>Leave it empty if you won't change members's password.</em></span>
                    <?php echo $form->error($model,'newPassword'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($model,'level'); ?><br>
                    <?php echo CHtml::dropDownList('User[level]',isset($model->level)?$model->level:'', User::levelList(),['class'=>'md-input','required'=>'required']); ?>
                    <?php echo $form->error($model,'level'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($model,'status'); ?><br>
                    <?php echo CHtml::dropDownList('User[status]',isset($model->status)?$model->status:'', User::statusList(),['class'=>'md-input','required'=>'required']); ?>
                    <?php echo $form->error($model,'status'); ?>
                </div>
                </div>
            </div>

protected/views/apps/user/_view.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

                            <?php if($model):?>
                                <?php $i=1; foreach($model as $row):?>
                                        <tr>
                                            <td><?=$i;?></td>
                                            <td><?=$row->name;?></td>
                                            <td><?= $row->email;?></td>
                                            <td><?= $row->levelname;?></td>
                                            <td><span class="uk-badge uk-badge-<?=($row->status==0)?'warning':'success';?>"><?= $row->statusname;?></span></td>
                                            <td><?= $row->last_login;?></td>
                                            <td class="uk-text-nowrap">
                                                <?php if($row->level!=='1'):?>
                                                    <?php echo CHtml::link('<i class="md-icon material-icons">&#xE254;</i>',array('update','id'=>$row->id));?>
                                                    <a href="#" class="del" data-id="<?php echo $row->id;?>"><i class="md-icon material-icons">&#xE872;</i></a>
                                                <?php endif;?>
                                            </td>
                                        </tr>
                                <?php $i++; endforeach;?>
                            <?php else:?>
                                        <tr>
                                            <td colspan="7"><p>User is unavailable.</p></td>
                                        </tr>
                            <?php endif; ?>

protected/views/apps/user/create.php
<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'validation',
    'enableAjaxValidation'=>false,
)); ?>
                            
    <div id="page_content">
            <div id="page_heading">
                <h1 id="product_edit_name">Add User</h1>
                <span class="uk-text-muted uk-text-upper uk-text-small" id="product_edit_sn"><?=$model->name;?></span>
            </div>
            <div id="page_content_inner">

                <?php Notify::renderFlash();?>
                <?php echo $this->renderPartial('_form', array('model'=>$model,'form'=>$form)); ?>
            </div>
    </div>

    <div class="md-fab-wrapper">
        <button type="submit" class="md-fab md-fab-success"><i class="material-icons">&#xE161;</i></button>
        <?=CHtml::link('<i class="material-icons">undo</i>','javascript: history.go(-1)',['class'=>'md-fab md-fab-warning']);?>
    </div>
<?php $this->endWidget(); ?>

protected/views/apps/user/index.php
<div id="page_content">
        <div id="page_content_inner">
            <h3 class="heading_b uk-margin-bottom">User Management</h3>
            <?php Notify::renderFlash();?>
            <div class="md-card">
                
                <div class="md-card-content">
                    <div class="uk-grid" data-uk-grid-margin>
                        
                        <div class="uk-width-1-1">
                            <div class="uk-overflow-container">
                                <table class="uk-table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Level</th>
                                            <th>Status</th>
                                            <th>Last Login</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $this->renderPartial('_view',array('model'=>$model));?>
                                    </tbody>
                                </table>
                            </div>
                            <?php if($count>10):?>
                            <div class="pagination center">
                            <?php 
                            $this->widget('CLinkPager', array(
                                'pages' => $pages,
                                'header'=>'',
                                'footer'=>'',
                                'nextPageLabel'=>'»',
                                'prevPageLabel'=>'«',
                                'id'=>'link_pager',
                            ))?>
                            </div>
                            <?php endif;?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

<div class="md-fab-wrapper">
        <a class="md-fab md-fab-accent" href="#new_data" data-uk-modal="{center:true}">
            <i class="material-icons">&#xE150;</i>
        </a>
    </div>

    <div class="uk-modal" id="new_data">
        <div class="uk-modal-dialog">
            <button class="uk-modal-close uk-close" type="button"></button>
            <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'form_validation',
                'action'=>Yii::app()->controller->createUrl('/apps/user/create'),
                'enableAjaxValidation'=>false,
                //'enableClientValidation'=>true
            )); ?>
                <?=CHtml::hiddenField('Category[type]',1);?>
                <div class="uk-modal-header">
                    <h3 class="uk-modal-title">Add New User</h3>
                </div>
                
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($newModel,'name'); ?>
                    <?php echo $form->textField($newModel,'name',array('maxlength'=>30,'class'=>'md-input','required'=>'required')); ?>
                    <?php echo $form->error($newModel,'name'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($newModel,'email'); ?>
                    <?php echo $form->emailField($newModel,'email',array('maxlength'=>50,'class'=>'md-input','required'=>'required')); ?>
                    <?php echo $form->error($newModel,'email'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($newModel,'password'); ?>
                    <?php echo $form->passwordField($newModel,'password',array('maxlength'=>30,'class'=>'md-input','required'=>'required')); ?>
                    <?php echo $form->error($newModel,'password'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($newModel,'level'); ?><br>
                    <?php echo CHtml::dropDownList('User[level]',isset($newModel->level)?$newModel->level:'', User::levelList(),['class'=>'md-input','required'=>'required']); ?>
                    <?php echo $form->error($newModel,'level'); ?>
                </div>
                <div class="uk-margin-large-bottom">
                    <?php echo $form->labelEx($newModel,'status'); ?><br>
                    <?php echo CHtml::dropDownList('User[status]',isset($newModel->status)?$newModel->status:'', User::statusList(),['class'=>'md-input','required'=>'required']); ?>
                    <?php echo $form->error($newModel,'status'); ?>
                </div>
                <div class="uk-modal-footer">
                    <button type="submit" class="uk-float-right md-btn md-btn-flat md-btn-flat-primary">Save</button>
                </div>
            <?php $this->endWidget(); ?>
        </div>
    </div>

<?php Yii::app()->clientScript->registerScript('delete-user', "
    $('.del').on('click',function(){
        if(!confirm('Are you sure want to delete this user?')) return false;
        var id=$(this).attr('data-id');
        $.ajax({
            url:'".$this->createUrl('apps/user/delete')."',
            type: 'GET',
            data: 'id='+id,
            success:function(){
                window.location.href = '".$this->createUrl('apps/user')."'; 
            }
        });
    return false;
    });
",CClientScript::POS_READY);?>

protected/views/apps/user/profile.php
<div id="page_content">
        <div id="page_content_inner">
            <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'validation',
                'enableAjaxValidation'=>false,
                'htmlOptions'=>array('enctype'=>'multipart/form-data','class'=>'uk-form-stacked'),
            )); ?>
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-large-12-12">
                        <div class="md-card">
                            <div class="user_heading" data-uk-sticky="{ top: 48, media: 960 }">
                                <div class="user_heading_avatar fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <?=CHtml::image($model->large_url,'');?>
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div class="user_avatar_controls">
                                        <span class="btn-file">
                                            <span class="fileinput-new"><i class="material-icons">&#xE2C6;</i></span>
                                            <span class="fileinput-exists"><i class="material-icons">&#xE86A;</i></span>
                                            <input type="file" name="User[avatar]" id="User[avatar]">
                                        </span>
                                        <a href="#" class="btn-file fileinput-exists" data-dismiss="fileinput">
                                            <i class="material-icons">&#xE5CD;</i>
                                        </a>
                                    </div>
                                </div>
                                <div class="user_heading_content">
                                    <h2 class="heading_b">
                                        <span class="uk-text-truncate" id="user_edit_uname">
                                            <?=$model->name;?>
                                        </span>
                                        <span class="sub-heading" id="user_edit_position"><?=$model->levelname;?></span>
                                    </h2>
                                </div>
                                <div class="md-fab-wrapper">
                                    <div class="md-fab md-fab-toolbar md-fab-small md-fab-accent">
                                        <i class="material-icons">&#xE8BE;</i>
                                        <div class="md-fab-toolbar-actions">
                                            <button type="submit" id="user_edit_save" data-uk-tooltip="{cls:'uk-tooltip-small',pos:'bottom'}" title="Save"><i class="material-icons md-color-white">&#xE161;</i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="user_content">
                                <ul id="user_edit_tabs" class="uk-tab" data-uk-tab="{connect:'#user_edit_tabs_content'}">
                                    <li class="uk-active"><a href="#">General info</a></li>
                                </ul>
                                <ul id="user_edit_tabs_content" class="uk-switcher uk-margin">
                                    <li>
                                        <div class="uk-margin-top">
                                            <div class="uk-grid" data-uk-grid-margin>
                                                <div class="uk-width-medium-1">
                                                    <label for="user_edit_uname_control">Full Name</label>
                                                    <?php echo $form->textField($model,'name',array('maxlength'=>30,'class'=>'md-input','required'=>'required')); ?>
                                                    <?php echo $form->error($model,'name'); ?>
                                                </div>
                                            </div>
                                            <div class="uk-grid" data-uk-grid-margin>
                                                <div class="uk-width-medium-1-2">
                                                    <label for="user_edit_uname_control">Email</label>
                                                    <?php echo $form->emailField($model,'email',array('maxlength'=>50,'class'=>'md-input','required'=>'required')); ?>
                                                    <?php echo $form->error($model,'email'); ?>
                                                </div>
                                                <div class="uk-width-medium-1-2">
                                                    <label for="user_edit_uname_control">New Password</label>
                                                    <?php echo $form->passwordField($model,'newPassword',array('maxlength'=>30,'class'=>'md-input')); ?><span><em>Leave it empty if you won't change your password.</em></span>
                                                    <?php echo $form->error($model,'newPassword'); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            <?php $this->endWidget(); ?>
        </div>
    </div>

protected/views/apps/user/update.php
<?php $form=$this->beginWidget('CActiveForm', array(
                                    'id'=>'validation',
                                    'enableAjaxValidation'=>false,
                            )); ?>
                            
    <div id="page_content">
            <div id="page_heading">
                <h1 id="product_edit_name">Edit User</h1>
                <span class="uk-text-muted uk-text-upper uk-text-small" id="product_edit_sn"><?=$model->name;?></span>
            </div>
            <div id="page_content_inner">

                <?php Notify::renderFlash();?>
                <?php echo $this->renderPartial('_form', array('model'=>$model,'form'=>$form)); ?>
            </div>
    </div>

    <div class="md-fab-wrapper">
        <button type="submit" class="md-fab md-fab-success"><i class="material-icons">&#xE161;</i></button>
        <?=CHtml::link('<i class="material-icons">undo</i>','javascript: history.go(-1)',['class'=>'md-fab md-fab-warning']);?>
    </div>
<?php $this->endWidget(); ?>

protected/views/apps/user/view.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */