protected/models/Category.php
<?php

/**
 * This is the model class for table "tbl_category".
 *
 * The followings are the available columns in table 'tbl_category':
 * @property string $id
 * @property string $name
 * @property string $slug
 * @property string $image
 * @property string $description
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 * @property string $type
 * @property integer $status
 * @property string $parent_id
 * @property string $created
 * @property string $modified
 *
 * The followings are the available model relations:
 * @property Category $parent
 * @property Category[] $categories
 * @property Content[] $contents
 * @property PageGroup[] $pageGroups
 */
class Category extends CActiveRecord
{
	const SMALL_THUMB_WIDTH=48;
	const SMALL_THUMB_HEIGHT=48;

	const MEDIUM_THUMB_WIDTH=300;
	const MEDIUM_THUMB_HEIGHT=225;

	const LARGE_THUMB_WIDTH=860;
	const LARGE_THUMB_HEIGHT=570;

	private $_small_url;
	private $_medium_url;
	private $_large_url;

	public function behaviors(){
	    return array(
		    'sluggable' => array(
			    'class'=>'ext.slug.SluggableBehavior',
			    'columns' => array('name'),
			    'unique' => true,
			    'update' => true,
		    ),
	  	);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_category';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('slug', 'length', 'max'=>100),
			array('image, meta_keywords', 'length', 'max'=>255),
			array('meta_title', 'length', 'max'=>70),
			array('meta_description', 'length', 'max'=>160),
			array('type', 'length', 'max'=>20),
			array('parent_id', 'length', 'max'=>10),
			array('description', 'safe'),
			['parent_id','default', 'value'=>null],
			['modified','setModified'],
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, slug, image, description, meta_title, meta_keywords, meta_description, type, status, parent_id, created, modified', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'parent' => array(self::BELONGS_TO, 'Category', 'parent_id'),
			'categories' => array(self::HAS_MANY, 'Category', 'parent_id'),
			'contents' => array(self::HAS_MANY, 'Content', 'category_id'),
			'pageGroups' => array(self::HAS_MANY, 'PageGroup', 'category_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'slug' => 'Slug',
			'image' => 'Image',
			'description' => 'Description',
			'meta_title' => 'Meta Title',
			'meta_keywords' => 'Meta Keywords',
			'meta_description' => 'Meta Description',
			'type' => 'Type',
			'status' => 'Status',
			'parent_id' => 'Parent',
			'created' => 'Created',
			'modified' => 'Modified',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('slug',$this->slug,true);
		$criteria->compare('image',$this->image,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('meta_title',$this->meta_title,true);
		$criteria->compare('meta_keywords',$this->meta_keywords,true);
		$criteria->compare('meta_description',$this->meta_description,true);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('parent_id',$this->parent_id,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('modified',$this->modified,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Category the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**/

	public function setModified()
    {
        if (!$this->isNewRecord) {
	        $this->modified = date('Y-m-d H:m:s');
        }

    }

	public function scopes()
	{
        return [
            'active'=>[
                'condition'=>'status=1',
            ],
            'null'=>[
                'condition'=>'parent_id is null',
            ],
            'notnull'=>[
                'condition'=>'parent_id is not null',
            ],
        ];
    }

    public function order($data)
    {
    	$this->getDbCriteria()->mergeWith([
    		'order'=>$data,
    		]);
    	return $this;
    }

    public function limit($data)
    {
    	$this->getDbCriteria()->mergeWith([
    		'limit'=>$data,
    		]);
    	return $this;
    }

    public function type($data)
    {
    	$this->getDbCriteria()->mergeWith([
    		'condition'=>'type=:tp',
    		'params'=>[':tp'=>$data]
    		]);
    	return $this;
    }

    public function slug($data)
    {
    	$this->getDbCriteria()->mergeWith([
    		'condition'=>'slug=:tp',
    		'params'=>[':slug'=>$data]
    		]);
    	return $this;
    }

    public function getStatusname()
    {
        switch($this->status)
        {
            case '1':
                return 'Active';
                break;
            case '0':
                return 'Not Active';
                break;
        }
    }
    
    public static function statusList()
    {
        return array(
            1=>'Active',
            0=>'Not Active'
        );
    }

    public function afterSave()
	{
        if(!empty($this->image))
        {
        	Yii::app()->hsnImage->generateThumb(self::SMALL_THUMB_WIDTH,self::SMALL_THUMB_HEIGHT,'categories',$this->type.$this->id,$this->image,'small');
        	Yii::app()->hsnImage->generateThumb(self::MEDIUM_THUMB_WIDTH,self::MEDIUM_THUMB_HEIGHT,'categories',$this->type.$this->id,$this->image,'medium');
        	Yii::app()->hsnImage->generateThumb(self::LARGE_THUMB_WIDTH,self::LARGE_THUMB_HEIGHT,'categories',$this->type.$this->id,$this->image,'large'); 
        }	           

	} 

	protected function beforeDelete() {
        parent::beforeDelete();
        Yii::app()->hsnImage->SureRemoveDir('categories',$this->type.$this->id);
        return TRUE;
    }

    public function getImgurl(){
        return Yii::app()->hsnImage->getUrl('categories',$this->type.$this->id).$this->image;
    }
        
    public function getSmall_url()
	{
		if($this->_small_url===NULL)
		{
			$this->_small_url=Yii::app()->hsnImage->generateThumbUrl($this->image,'categories',$this->type.$this->id,'small');
		}
		return Yii::app()->baseUrl.'/'.$this->_small_url;
	}

	public function getMedium_url()
	{
		if($this->_medium_url===NULL)
		{
			$this->_medium_url=Yii::app()->hsnImage->generateThumbUrl($this->image,'categories',$this->type.$this->id,'medium');
		}
		return Yii::app()->baseUrl.'/'.$this->_medium_url;
	}

	public function getLarge_url()
	{
		if($this->_large_url===NULL)
		{
			$this->_large_url=Yii::app()->hsnImage->generateThumbUrl($this->image,'categories',$this->type.$this->id,'large');
		}
		return Yii::app()->baseUrl.'/'.$this->_large_url;
	}
}

protected/views/apps/category/_form.php
<?=$form->errorSummary($model);?>
<div class="uk-grid" data-uk-grid-margin>
	<div class="uk-width-medium-1-2">
		<div class="md-card">
			<div class="md-card-content large-padding">
				<?php if ($type!=='page'):?>
				<div class="uk-form-row">
					<div class="uk-width-medium-1-1">
	                    <?= $form->dropDownList($model,'parent_id',CHtml::ListData($parents,'id','name'),['prompt'=>'Select Parent','data-md-selectize'=>'true']);?>
						<?php echo $form->error($model,'parent_id'); ?>
					</div>
				</div>
				<?php endif;?>
				
				<div class="uk-form-row">
					<?php echo $form->labelEx($model,'name'); ?>
					<?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50,'class'=>'md-input')); ?>
					<?php echo $form->error($model,'name'); ?>
				</div>

				<div class="uk-form-row">
					<?php echo $form->labelEx($model,'image'); ?><br>
					<?php if ($model->image):?>
						<?=CHtml::image($model->small_url);?>
					<?php endif;?>
					<?php echo $form->fileField($model,'image',array('size'=>60,'maxlength'=>255,'class'=>'md-input')); ?>
					<?php echo $form->error($model,'image'); ?>
				</div>

				<div class="uk-form-row">
					<?php echo $form->labelEx($model,'description'); ?>
					<?php echo $form->textArea($model,'description',array('row'=>6, 'cols'=>50,'class'=>'md-input')); ?>
					<?php echo $form->error($model,'description'); ?>
				</div>

			</div>
		</div>
	</div>
	<div class="uk-width-medium-1-2">
		<div class="md-card">
            <div class="md-card-content">
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-3 uk-width-large-1-3">
	                    <?php echo $form->checkbox($model,'status',['data-switchery'=>'true']); ?>
                        <label class="inline-label">Is Active</label>
                    </div>
                </div>
            </div>
        </div>
		<div class="md-card">
			<div class="md-card-content large-padding">
				<div class="uk-form-row">
					<?php echo $form->labelEx($model,'meta_title'); ?>
					<?php echo $form->textField($model,'meta_title',array('size'=>60,'maxlength'=>70,'class'=>'md-input')); ?>
					<?php echo $form->error($model,'meta_title'); ?>
				</div>

				<div class="uk-form-row">
					<?php echo $form->labelEx($model,'meta_keywords'); ?>
					<?php echo $form->textField($model,'meta_keywords',array('size'=>60,'maxlength'=>255,'class'=>'md-input')); ?>
					<?php echo $form->error($model,'meta_keywords'); ?>
				</div>

				<div class="uk-form-row">
					<?php echo $form->labelEx($model,'meta_description'); ?>
					<?php echo $form->textField($model,'meta_description',array('size'=>60,'maxlength'=>160,'class'=>'md-input')); ?>
					<?php echo $form->error($model,'meta_description'); ?>
				</div>
			</div>
		</div>
	</div>
</div>

protected/views/apps/category/create.php
<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'validation',
    'enableAjaxValidation'=>false,
    'htmlOptions'=>array('enctype'=>'multipart/form-data','class'=>'uk-form-stacked'),
)); ?>
                            
    <div id="page_content">
            <div id="page_heading">
                <h1 id="product_edit_name">Add <?=ucfirst($type);?> Category</h1>
                <span class="uk-text-muted uk-text-upper uk-text-small" id="product_edit_sn"><?=$model->name;?></span>
            </div>
            
            <div id="page_content_inner">

                <?php Notify::renderFlash();?>
                <?php echo $this->renderPartial('_form', array('model'=>$model,'form'=>$form,'type'=>$type,'parents'=>$parents)); ?>
            </div>
    </div>

    <div class="md-fab-wrapper">
        <button type="submit" class="md-fab md-fab-success"><i class="material-icons">&#xE161;</i></button>
    </div>
<?php $this->endWidget(); ?>

protected/views/apps/category/index.php
<div id="page_content">
        <div id="page_content_inner">
            <h3 class="heading_b uk-margin-bottom"><?=ucfirst($type);?> Categories</h3>
            <?php Notify::renderFlash();?>
            <div class="md-card">                
                <div class="md-card-content">
                    <div class="uk-grid" data-uk-grid-margin>
                        <div class="uk-width-1-1">
                            <div class="uk-overflow-container">
                                <table class="uk-table">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Slug</th>
                                            <th>Active</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if($parents):?>
			                                <?php $i=1; foreach($parents as $data):?>
		                                        <tr>
		                                            <td class="uk-text-large uk-text-nowrap"><?=$data->name;?></td>
		                                            <td class="uk-text-large uk-text-nowrap"><?= $data->slug;?></td>
                                                    <td>
                                                        <?php if($data->status):?>
                                                            <i class="material-icons uk-text-success md-24">&#xE834;</i>
                                                        <?php else:?>
                                                            <i class="material-icons uk-text-muted md-24">&#xE835;</i>
                                                        <?php endif;?>
                                                    </td>
		                                            <td>
	                                                    <?php echo CHtml::link('<i class="md-icon material-icons">&#xE254;</i>',array('update','id'=>$data->id));?>
	                                                    <?php if (!$data->categories):?>
	                                                    <a href="#" class="del" data-id="<?php echo $data->id;?>"><i class="md-icon material-icons">&#xE872;</i></a>
	                                                	<?php endif;?>
		                                            </td>
		                                        </tr>
		                                        <?php if ($data->categories):?>
		                                        	<?php $ii=1; foreach($data->categories as $data):?>
			                                        <tr>
                                                        <td class="uk-text-large uk-text-nowrap">____ <?=$data->name;?></td>
			                                            <td class="uk-text-large uk-text-nowrap"><?= $data->slug;?></td>
			                                            <td>
                                                            <?php if($data->status):?>
                                                                <i class="material-icons uk-text-success md-24">&#xE834;</i>
                                                            <?php else:?>
                                                                <i class="material-icons uk-text-muted md-24">&#xE835;</i>
                                                            <?php endif;?>
                                                        </td>
			                                            <td>
		                                                    <?php echo CHtml::link('<i class="md-icon material-icons">&#xE254;</i>',array('update','id'=>$data->id));?>
		                                                    <a href="#" class="del" data-id="<?php echo $data->id;?>"><i class="md-icon material-icons">&#xE872;</i></a>
			                                            </td>
			                                        </tr>
			                                        <?php $ii++; endforeach;?>
		                                    	<?php endif;?>
		                                    <?php $i++; endforeach;?>
			                            <?php else:?>
	                                        <tr>
	                                            <td colspan="6"><p><?=ucfirst($type);?> Category is unavailable.</p></td>
	                                        </tr>
			                            <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                            <div class="pagination center">
                            <?php 
                            $this->widget('CLinkPager', array(
                                'pages' => $pages,
                                'header'=>'',
                                'footer'=>'',
                                'nextPageLabel'=>'»',
                                'prevPageLabel'=>'«',
                                'id'=>'link_pager',
                            ))?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

	<div class="md-fab-wrapper">
        <?=CHtml::link('<i class="material-icons">&#xE150;</i>', ['create','type'=>$type],['class'=>'md-fab md-fab-accent']);?>
    </div>    

<?php Yii::app()->clientScript->registerScript('delete', "
    $('.del').on('click',function(){
        if(!confirm('Are you sure want to delete the selected item?')) return false;
        var id=$(this).attr('data-id');
        $.ajax({
            url:'".$this->createUrl('apps/category/delete')."',
            type: 'GET',
            data: 'id='+id,
            success:function(){
                window.location.href = '".$this->createUrl('apps/category',['type'=>$type])."'; 
            }
        });
    return false;
    });
",CClientScript::POS_READY);?>

protected/views/apps/category/update.php
<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'validation',
    'enableAjaxValidation'=>false,
    'htmlOptions'=>array('enctype'=>'multipart/form-data','class'=>'uk-form-stacked'),
)); ?>
                            
    <div id="page_content">
            <div id="page_heading">
                <h1 id="product_edit_name">Update <?=ucfirst($type);?> Category</h1>
                <span class="uk-text-muted uk-text-upper uk-text-small" id="product_edit_sn"><?=$model->name;?></span>
            </div>
            
            <div id="page_content_inner">

                <?php Notify::renderFlash();?>
                <?php echo $this->renderPartial('_form', array('model'=>$model,'form'=>$form,'type'=>$type,'parents'=>$parents)); ?>
            </div>
    </div>

    <div class="md-fab-wrapper">
        <button type="submit" class="md-fab md-fab-success"><i class="material-icons">&#xE161;</i></button>
    </div>
<?php $this->endWidget(); ?>